 # Use Python base image
FROM python:3.10

# Set working directory
WORKDIR /app

# Copy necessary files
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy the script
COPY producer.py .

# Command to run
CMD ["python", "producer.py"]
